---

- hosts: localhost
  connection: local

  vars_files:
    - variables.yml

  tasks:

    - name: EC2 info and filter for running ansible tag name
      ec2_instance_info:
        filters:
          "tag:Name": "{{ ec2_name }}"
          instance-state-name: running
      register: ec2

    - name: Terminate EC2 Instance
      ec2_instance:
        state: absent
      with_items: "{{ ec2.instances }}"

    - name: Delete Key Pair
      ec2_key:
        name: "{{ key_name }}"
        state: absent

    - name: "Delete group by its id"
      ec2_group:
        name: "{{ security_group }}"
        state: absent

