# Ansible Config
ansible_ssh_private_key_file: /Users/mk/.ssh/ansibleKey


# General
ansible_tag: ansible

# EC2
ec2_name: Hello-Ansible
key_name: ansibleKey
image_id: ami-0915e09cc7ceee3ab

# Security Group
security_group: sg_ansible

# App Container
container_name: hello
image_name: nginx
host_port: 80
container_port: 80

